name: Makefile CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: make setup
      run: make setup

    - name: make check-all
      run: make check-all

    - name: List files in the repository
      run: |
        ls ${{ github.workspace }}
